import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import Client from '../components/client'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container mt-3">
        <div className='row'>
          <div className='col'>   
            <h3>VJT Build Tools</h3>
          </div>
        </div>
      </div>
    </>
  )
}
